CREATE TABLE IF NOT EXISTS `USER` (
    USER_ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_DT DATETIME(6) NOT NULL,
    MODIFIED_DT DATETIME(6) NULL,
    NICKNAME VARCHAR(255) NOT NULL COMMENT '닉네임',
    ACCOUNT_TYPE VARCHAR(255) NOT NULL COMMENT '계정 타입 ( LESSOR : 임대인, REALTOR : 공인 중개사, LESSEE : 임차인 )',
    ACCOUNT_ID VARCHAR(255) NOT NULL COMMENT '계정 ID',
    QUIT BIT(1) NOT NULL COMMENT '탈퇴 여부',
    UNIQUE (NICKNAME,ACCOUNT_ID)
);


CREATE TABLE IF NOT EXISTS BOARD (
    BOARD_ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_DT DATETIME(6) NOT NULL,
    MODIFIED_DT DATETIME(6) NULL,
    BOARD_TITLE VARCHAR(255) NOT NULL COMMENT '게시판 제목',
    BOARD_CONTENT TEXT NOT NULL COMMENT '게시판 내용',
    USER_ID BIGINT(20) NOT NULL COMMENT '게시판 등록자',
    ENABLED BIT(1) NOT NULL COMMENT '사용여부'
);

CREATE TABLE IF NOT EXISTS NICE (
    NICE_ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_DT DATETIME(6) NOT NULL,
    MODIFIED_DT DATETIME(6) NULL,
    BOARD_ID BIGINT(20) NOT NULL COMMENT '게시판 ID',
    USER_ID BIGINT(20) NOT NULL COMMENT '사용자 아이디',
    ENABLED BIT(1) NOT NULL COMMENT '사용여부'
);
